// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// dirnet_posterior_cpp
Rcpp::List dirnet_posterior_cpp(arma::mat edgelist_, bool include_mu_, bool include_theta_, bool include_gamma_, arma::vec mu_, arma::vec theta_, arma::vec gamma_, double tau_eta_, double tau_theta_, double tau_gamma_, double sigma_mu_, double a_eta_, double b_eta_, double a_theta_, double b_theta_, double a_gamma_, double b_gamma_, unsigned int burnin_, unsigned int thin_, unsigned int net_n_iter_, arma::vec proposal_mu_, arma::vec proposal_theta_, arma::vec proposal_gamma_, bool verbose_);
RcppExport SEXP _DirNet_dirnet_posterior_cpp(SEXP edgelist_SEXP, SEXP include_mu_SEXP, SEXP include_theta_SEXP, SEXP include_gamma_SEXP, SEXP mu_SEXP, SEXP theta_SEXP, SEXP gamma_SEXP, SEXP tau_eta_SEXP, SEXP tau_theta_SEXP, SEXP tau_gamma_SEXP, SEXP sigma_mu_SEXP, SEXP a_eta_SEXP, SEXP b_eta_SEXP, SEXP a_theta_SEXP, SEXP b_theta_SEXP, SEXP a_gamma_SEXP, SEXP b_gamma_SEXP, SEXP burnin_SEXP, SEXP thin_SEXP, SEXP net_n_iter_SEXP, SEXP proposal_mu_SEXP, SEXP proposal_theta_SEXP, SEXP proposal_gamma_SEXP, SEXP verbose_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type edgelist_(edgelist_SEXP);
    Rcpp::traits::input_parameter< bool >::type include_mu_(include_mu_SEXP);
    Rcpp::traits::input_parameter< bool >::type include_theta_(include_theta_SEXP);
    Rcpp::traits::input_parameter< bool >::type include_gamma_(include_gamma_SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu_(mu_SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_(theta_SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gamma_(gamma_SEXP);
    Rcpp::traits::input_parameter< double >::type tau_eta_(tau_eta_SEXP);
    Rcpp::traits::input_parameter< double >::type tau_theta_(tau_theta_SEXP);
    Rcpp::traits::input_parameter< double >::type tau_gamma_(tau_gamma_SEXP);
    Rcpp::traits::input_parameter< double >::type sigma_mu_(sigma_mu_SEXP);
    Rcpp::traits::input_parameter< double >::type a_eta_(a_eta_SEXP);
    Rcpp::traits::input_parameter< double >::type b_eta_(b_eta_SEXP);
    Rcpp::traits::input_parameter< double >::type a_theta_(a_theta_SEXP);
    Rcpp::traits::input_parameter< double >::type b_theta_(b_theta_SEXP);
    Rcpp::traits::input_parameter< double >::type a_gamma_(a_gamma_SEXP);
    Rcpp::traits::input_parameter< double >::type b_gamma_(b_gamma_SEXP);
    Rcpp::traits::input_parameter< unsigned int >::type burnin_(burnin_SEXP);
    Rcpp::traits::input_parameter< unsigned int >::type thin_(thin_SEXP);
    Rcpp::traits::input_parameter< unsigned int >::type net_n_iter_(net_n_iter_SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type proposal_mu_(proposal_mu_SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type proposal_theta_(proposal_theta_SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type proposal_gamma_(proposal_gamma_SEXP);
    Rcpp::traits::input_parameter< bool >::type verbose_(verbose_SEXP);
    rcpp_result_gen = Rcpp::wrap(dirnet_posterior_cpp(edgelist_, include_mu_, include_theta_, include_gamma_, mu_, theta_, gamma_, tau_eta_, tau_theta_, tau_gamma_, sigma_mu_, a_eta_, b_eta_, a_theta_, b_theta_, a_gamma_, b_gamma_, burnin_, thin_, net_n_iter_, proposal_mu_, proposal_theta_, proposal_gamma_, verbose_));
    return rcpp_result_gen;
END_RCPP
}
// dirnet_GS_cpp
Rcpp::List dirnet_GS_cpp(arma::mat edgelist_, bool include_mu_, bool include_theta_, bool include_gamma_, arma::vec mu_, arma::vec theta_, arma::vec gamma_, double tau_eta_, double tau_theta_, double tau_gamma_, double sigma_mu_, double a_eta_, double b_eta_, double a_theta_, double b_theta_, double a_gamma_, double b_gamma_, unsigned int burnin_, unsigned int thin_, unsigned int net_n_iter_, arma::vec proposal_mu_, arma::vec proposal_theta_, arma::vec proposal_gamma_, bool verbose_);
RcppExport SEXP _DirNet_dirnet_GS_cpp(SEXP edgelist_SEXP, SEXP include_mu_SEXP, SEXP include_theta_SEXP, SEXP include_gamma_SEXP, SEXP mu_SEXP, SEXP theta_SEXP, SEXP gamma_SEXP, SEXP tau_eta_SEXP, SEXP tau_theta_SEXP, SEXP tau_gamma_SEXP, SEXP sigma_mu_SEXP, SEXP a_eta_SEXP, SEXP b_eta_SEXP, SEXP a_theta_SEXP, SEXP b_theta_SEXP, SEXP a_gamma_SEXP, SEXP b_gamma_SEXP, SEXP burnin_SEXP, SEXP thin_SEXP, SEXP net_n_iter_SEXP, SEXP proposal_mu_SEXP, SEXP proposal_theta_SEXP, SEXP proposal_gamma_SEXP, SEXP verbose_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type edgelist_(edgelist_SEXP);
    Rcpp::traits::input_parameter< bool >::type include_mu_(include_mu_SEXP);
    Rcpp::traits::input_parameter< bool >::type include_theta_(include_theta_SEXP);
    Rcpp::traits::input_parameter< bool >::type include_gamma_(include_gamma_SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu_(mu_SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_(theta_SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gamma_(gamma_SEXP);
    Rcpp::traits::input_parameter< double >::type tau_eta_(tau_eta_SEXP);
    Rcpp::traits::input_parameter< double >::type tau_theta_(tau_theta_SEXP);
    Rcpp::traits::input_parameter< double >::type tau_gamma_(tau_gamma_SEXP);
    Rcpp::traits::input_parameter< double >::type sigma_mu_(sigma_mu_SEXP);
    Rcpp::traits::input_parameter< double >::type a_eta_(a_eta_SEXP);
    Rcpp::traits::input_parameter< double >::type b_eta_(b_eta_SEXP);
    Rcpp::traits::input_parameter< double >::type a_theta_(a_theta_SEXP);
    Rcpp::traits::input_parameter< double >::type b_theta_(b_theta_SEXP);
    Rcpp::traits::input_parameter< double >::type a_gamma_(a_gamma_SEXP);
    Rcpp::traits::input_parameter< double >::type b_gamma_(b_gamma_SEXP);
    Rcpp::traits::input_parameter< unsigned int >::type burnin_(burnin_SEXP);
    Rcpp::traits::input_parameter< unsigned int >::type thin_(thin_SEXP);
    Rcpp::traits::input_parameter< unsigned int >::type net_n_iter_(net_n_iter_SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type proposal_mu_(proposal_mu_SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type proposal_theta_(proposal_theta_SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type proposal_gamma_(proposal_gamma_SEXP);
    Rcpp::traits::input_parameter< bool >::type verbose_(verbose_SEXP);
    rcpp_result_gen = Rcpp::wrap(dirnet_GS_cpp(edgelist_, include_mu_, include_theta_, include_gamma_, mu_, theta_, gamma_, tau_eta_, tau_theta_, tau_gamma_, sigma_mu_, a_eta_, b_eta_, a_theta_, b_theta_, a_gamma_, b_gamma_, burnin_, thin_, net_n_iter_, proposal_mu_, proposal_theta_, proposal_gamma_, verbose_));
    return rcpp_result_gen;
END_RCPP
}
