# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dirnet_posterior_cpp <- function(edgelist_, include_mu_, include_theta_, include_gamma_, mu_, theta_, gamma_, tau_eta_, tau_theta_, tau_gamma_, sigma_mu_, a_eta_, b_eta_, a_theta_, b_theta_, a_gamma_, b_gamma_, burnin_, thin_, net_n_iter_, proposal_mu_, proposal_theta_, proposal_gamma_, verbose_) {
    .Call(`_DirNet_dirnet_posterior_cpp`, edgelist_, include_mu_, include_theta_, include_gamma_, mu_, theta_, gamma_, tau_eta_, tau_theta_, tau_gamma_, sigma_mu_, a_eta_, b_eta_, a_theta_, b_theta_, a_gamma_, b_gamma_, burnin_, thin_, net_n_iter_, proposal_mu_, proposal_theta_, proposal_gamma_, verbose_)
}

dirnet_GS_cpp <- function(edgelist_, include_mu_, include_theta_, include_gamma_, mu_, theta_, gamma_, tau_eta_, tau_theta_, tau_gamma_, sigma_mu_, a_eta_, b_eta_, a_theta_, b_theta_, a_gamma_, b_gamma_, burnin_, thin_, net_n_iter_, proposal_mu_, proposal_theta_, proposal_gamma_, verbose_) {
    .Call(`_DirNet_dirnet_GS_cpp`, edgelist_, include_mu_, include_theta_, include_gamma_, mu_, theta_, gamma_, tau_eta_, tau_theta_, tau_gamma_, sigma_mu_, a_eta_, b_eta_, a_theta_, b_theta_, a_gamma_, b_gamma_, burnin_, thin_, net_n_iter_, proposal_mu_, proposal_theta_, proposal_gamma_, verbose_)
}

